### ISSUE TITLE
File x_stdgraph.x is missing from the set of source files

### ISSUE THREAD

**Issue by SnoBotics981** [steelewool/iraf#17]
As of 4/26/17 my build is failing because it can't find this file. Here is the text from the spool file:

xc -c -w -/g -/m64 x_stdgraph.x
x_stdgraph.x:
   sys_runtask:
x_stdgraph.f:
   sysruk:
xc -Nz   -/g -/m64 x_stdgraph.o -lstg
/home/steele/git/iraf/lib/libcfitsio.a: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Warning, mkpkg line 9: module `relink' not found or returned error
move `x_stdgraph.e' to `bin$x_stdgraph.e'
$move: file `x_stdgraph.e' not found
Warning, mkpkg line 19: error moving file x_stdgraph.e
Warning, mkpkg line 10: module `install' not found or returned error
xc -c -w -/g -/m64 x_sgikern.x
x_sgikern.x:
   sys_runtask:
x_sgikern.f:
   sysruk:
xc -Nz   -/g -/m64 x_sgikern.o -lsgi
/home/steele/git/iraf/lib/libcfitsio.a: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Warning, mkpkg line 10: module `relink' not found or returned error
move `x_sgikern.e' to `bin$x_sgikern.e'

**Comment by RobSteele49** [comment]
My bad - the problem isn't with x_stdgraph.x but rather the version of libcfitsio.a in /lib is bad.

steele@steele-VirtualBox:~/git/iraf$ ls -lt lib/libcfitsio.a 
-rw-r--r-- 1 steele steele 0 Oct 19  2013 lib/libcfitsio.a
steele@steele-VirtualBox:~/git/iraf$ ls -lt bin.linux64/libcfitsio.a 
-rw-rw-r-- 1 steele steele 8825552 Apr 26 07:22 bin.linux64/libcfitsio.a
