### ISSUE TITLE
Test recompiling iraf

### ISSUE THREAD

**Issue by RobSteele49** [steelewool/iraf#2]
We need to make some minor but obvious change to the code. Then recompile, reinstall, and test to make sure the change is incorporated and we have a way forward to start modifying the code.

**Comment by RobSteele49** [comment]
At the top level, in my case, /home/steele/git/iraf, I just tried make with no options. This ran for a long time with several fatal errors indicated. I need to do this and log the logput. It did run for about 5 minutes and there were not error messages at the end. I executed the following command and there was able to run cl, ecl, and iraf with no obvious errors.

 1984  rm -rf .iraf
 1986  rm -rf .imtoolrc 
 1989  ./install

The make did create lots of .o files and modified the .a files.

**Comment by RobSteele49** [comment]
Tried with the following make options:

 2130  make linux64
 2131  make sysgen

At the end got the messages:

   Building CFITSIO libs ....done
    Building Readline libs ....mkpkg: Command not found.
done
    Building VOClient libs ....done
make[1]: Leaving directory '/home/steele/git/iraf/vendor'
util/mksysgen: line 60: mkpkg: command not found
util/mksysgen: line 64: mkpkg: command not found
util/mksysgen: line 68: mkpkg: command not found

The did the .install and got the errors:

Start:  Tue Apr 18 13:36:34 PDT 2017
  End:  Tue Apr 18 13:37:55 PDT 2017
                       Checking File Permissions
                       -------------------------
Checking iraf file permissions ...                             [ FAIL ]
   ***  File
   ***  File
   ***  File
   ***  File
   ***  File
   ***  File
   ***  File

And to no surprise cl, ecl, and iraf all did not work.

When I tried running make this failed as well.

**Comment by RobSteele49** [comment]
As I'm not getting similar errors when I try and use the tar balls I'm going back to just running from this repository with the goal is to fix things. I'm assuming I'll learn a lot about how IRAF is put together along the way.

**Comment by RobSteele49** [comment]
Checked out a clean version. Did a ./install per the README.install and then tried 'make linux64' and got:

steele@steele-VirtualBox:~/git/iraf$ make linux64
(util/mkarch linux64)
Making architecture: 
~/.cshrc
compress: Command not found.
deleting any dreg .e files left lying about in the source directories... done
archiving and deleting generic objects... old objects will not be archived as no bin.generic directory found

restoring archived linux64 objects... done
/bin/bash: setenv: command not found
~/.cshrc
compress: Command not found.
deleting any dreg .e files left lying about in the source directories... done
archiving and deleting generic objects... old objects will not be archived as no bin.generic directory found

restoring archived linux64 objects... done
~/.cshrc
compress: Command not found.
deleting any dreg .e files left lying about in the source directories... done

----
So at a minimum it looks like I'm missing compress.

**Comment by RobSteele49** [comment]
Got rid of the compress error by installing it. The command was:

sudo apt-get install ncompress

**Comment by steelewool** [comment]
Will track each of the problems with building the software. Will be closing out the generic issue for now.

**Comment by RobSteele49** [comment]
Updated README.install to include how to install compress.
